require("options")
require("keymaps")

require("plugins.lazy")
require("plugins.appearance")
require("plugins.essentials")
require("plugins.git")
require("plugins.lsp")
require("plugins.qol")
require("plugins.options")
require("plugins.keymaps")
